sudo: false
language: java
jdk:
- openjdk7
cache:
  directories:
  - itests/.cargo
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_594de081de2f_key -iv $encrypted_594de081de2f_iv
  -in travis-encrypted.tar.enc -out travis-encrypted.tar -d
- tar xvf travis-encrypted.tar
- unset GEM_PATH
install: true
branches:
  except:
  - master
matrix:
  fast_finish: true
env:
  global:
  - secure: nSldmFh+YCDB2zErXTzy2wkTnw7QLDGYR53apjR7N033WyotFHM8suiVUkFN1OCw1b7qTk2FnikJ5+5KbiI5wxm+4v07Qc0MQtBAV7bdeE1efLgdp335L2/DETSEY+Hiz6WQThmMOYooM1Z0qn3UO80fGiGD9FMkShbmQKuGUe4=
  - secure: DgqS4PrNEmnOblJNe+qeSGsiOtVb5qMgEtTrMD1Y+FdOyWER/orgMOGDWy/xtbbS1dbaCmATOdRxsvXJqRrPaNZLcWZ8e+9d/L3XWYmoBRaGDiH1eVjUUibK79xOUyrBChLCEOkgfuIKHr3nkiPfDWRb5a6CsNn0cbPu56+8j64=
  - secure: TjZNKclYzXO4CaiJI0NsDAOTYbVXUjU7db/4Pgx00eNCQxJMEmdt3sdzt5r5bRQtB4rPWGKa9Ki4wfd+MMHAa987bjIwSTzBXiCG8+LJNutdCTDXk446dmgsAWWjF39Y4kfnagZ/qbxEiVb+9+ixfrLyNKhvVDE34y26ySrxdZg=
  - secure: WUWchzcdGrC6aifA9DuztFPpJLjrns/4ymIzHmjIjLWVXvXGEYnNhbgbH76hW5wFl89Ve8YMvHBcF50P++sRD1HwHSF6naDoiASpmHxAKBnyKJvdxgo06DMygMqlrg8zwEk0Ilh1nF9m5KGEEYLggxQLZEi2dXMANPZs3wR5qOY=
  matrix:
  - goals=verify package=store use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=environment use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=forge use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/forum use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/materials use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/groups use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/index use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/pages use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/participants use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/settings use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=illusion/templates use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=gamelibrary use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  - goals=verify package=forum use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
  
  - goals=verify package=store use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=environment use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=forge use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/forum use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/materials use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/groups use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/pages use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/participants use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/settings use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=illusion/templates  use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=gamelibrary use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  - goals=verify package=forum use_sc=true it_profile=travis it_browser="chrome" it_browser_version="46" it_platform="Linux"
  
  - goals=verify package=store use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=environment use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=forge use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/forum use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/materials use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/groups use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/index use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/pages use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/participants use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/settings use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=illusion/templates use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=gamelibrary use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  - goals=verify package=forum use_sc=true it_profile=travis it_browser="safari" it_browser_version="8.0" it_platform="OS X 10.10"
  
  - goals=verify package=store use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=environment use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=forge use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/forum use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/materials use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/groups use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/index use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/pages use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/participants use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/settings use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=illusion/templates use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=gamelibrary use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  - goals=verify package=forum use_sc=true it_profile=travis it_browser="firefox" it_browser_version="41.0" it_platform="Windows 8"
  
  - goals=verify package=store use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=environment use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=forge use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/forum use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/materials use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/groups use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/index use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/pages use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/participants use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/settings use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=illusion/templates use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=gamelibrary use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  - goals=verify package=forum use_sc=true it_profile=travis it_browser="internet explorer" it_browser_version="11.0" it_platform="Windows 8.1"
  
  - goals=verify use_sc=false it_profile=rest

before_script:
- if [ $use_sc = true ]; then curl -sS https://saucelabs.com/downloads/sc-4.3.13-linux.tar.gz|tar -xzC /tmp/; fi;
- if [ $use_sc = true ]; then /tmp/sc-4.3.13-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_NUMBER --vm-version dev-varnish -B *.facebook.com --daemonize --readyfile /tmp/sc-ready --wait-tunnel-shutdown; fi;
- if [ $use_sc = true ]; then 
    t=0;
    while [ ! -f /tmp/sc-ready ]; do 
      sleep 0.5; 
      t=$((t+1)); 
      if [ $t -gt 180 ]; then 
        killall sc;
        echo "Unable to get Sauce connection within 3 minutes";
        exit 1;
      fi;
    done;
  fi;
script: 
  mvn $goals 
    -P$it_profile 
    -Dexec.args="-Duser.timezone=UTC" 
    -Dmaven.javadoc.skip=true 
    -Dsource.skip=true 
    -Dit.properties.file=src/test/resources/it-travis.properties 
    -Dit.package=$package 
    -Dit.browser="$it_browser"
    -Dit.browser.version="$it_browser_version"
    -Dit.platform="$it_platform"
after_success:
- if [ $use_sc = true ]; then killall sc; fi;
- if [ $TRAVIS_BRANCH = 'devel' ]; then python travis/m2conf.py; fi;
- if [ $TRAVIS_BRANCH = 'devel' ]; then mvn deploy --settings ~/.m2/mySettings.xml; fi;
after_failure:
- if [ $use_sc = true ]; then killall sc; fi;
- cat itests/target/cargo/configurations/wildfly8x/log/server.log
        
