sudo: false
language: java
jdk:
- openjdk7
cache:
  directories:
  - itests/.cargo
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_594de081de2f_key -iv $encrypted_594de081de2f_iv
  -in travis-encrypted.tar.enc -out travis-encrypted.tar -d
- tar xvf travis-encrypted.tar
- unset GEM_PATH
branches:
  except:
  - master
env:
  global:
  - secure: nSldmFh+YCDB2zErXTzy2wkTnw7QLDGYR53apjR7N033WyotFHM8suiVUkFN1OCw1b7qTk2FnikJ5+5KbiI5wxm+4v07Qc0MQtBAV7bdeE1efLgdp335L2/DETSEY+Hiz6WQThmMOYooM1Z0qn3UO80fGiGD9FMkShbmQKuGUe4=
  - secure: DgqS4PrNEmnOblJNe+qeSGsiOtVb5qMgEtTrMD1Y+FdOyWER/orgMOGDWy/xtbbS1dbaCmATOdRxsvXJqRrPaNZLcWZ8e+9d/L3XWYmoBRaGDiH1eVjUUibK79xOUyrBChLCEOkgfuIKHr3nkiPfDWRb5a6CsNn0cbPu56+8j64=
  - secure: TjZNKclYzXO4CaiJI0NsDAOTYbVXUjU7db/4Pgx00eNCQxJMEmdt3sdzt5r5bRQtB4rPWGKa9Ki4wfd+MMHAa987bjIwSTzBXiCG8+LJNutdCTDXk446dmgsAWWjF39Y4kfnagZ/qbxEiVb+9+ixfrLyNKhvVDE34y26ySrxdZg=
  - secure: WUWchzcdGrC6aifA9DuztFPpJLjrns/4ymIzHmjIjLWVXvXGEYnNhbgbH76hW5wFl89Ve8YMvHBcF50P++sRD1HwHSF6naDoiASpmHxAKBnyKJvdxgo06DMygMqlrg8zwEk0Ilh1nF9m5KGEEYLggxQLZEi2dXMANPZs3wR5qOY=
  matrix:
  - it_browsers="chrome:45:Linux"
  - it_browsers="safari:8.1:OS X 10.11"
  - it_browsers="firefox:41.0:Windows 8"
  - it_browsers="internet explorer:11.0:Windows 8.1"
  - it_browsers="microsoftedge:20.10240:Windows 10"
addons:
  sauce_connect:
    tunnel_domains: test.forgeandillusion.net,custom-test.forgeandillusion.net
script: mvn test verify -Ptravis -Dexec.args="-Duser.timezone=UTC" -Dit.browsers=$it_browsers
after_success:
- python travis/m2conf.py
- mvn deploy --settings ~/.m2/mySettings.xml
